### ISSUE TITLE
Support HTTP/2 server push

### ISSUE THREAD

**Issue by myml** [go-macaron/macaron#136]
about http2 push

reference [HTTP/2 Server Push](https://blog.golang.org/h2push)

    **http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        if pusher, ok := w.(http.Pusher); ok {
            // Push is supported.
            if err := pusher.Push("/app.js", nil); err != nil {
                log.Printf("Failed to push: %v", err)
            }
        }
        // ...
    })**

below is my code
```
	m := macaron.New()
	m.Get("/", func(ctx *macaron.Context) {
		if push, ok := ctx.Resp.(http.Pusher); ok {
			log.Println("ok", push)
		} else {
			log.Println("no")
		}
	})
	m.Get("/pushTest", func(w http.ResponseWriter, r *http.Request) {
		if pusher, ok := w.(http.Pusher); ok {
			log.Println("ok", pusher)
		} else {
			log.Println("no")
		}
	})
	log.Panic(http.ListenAndServeTLS(":1234", "server.crt", "server.key", m))
```
output is always `no`.Do not support it

**Comment by jeffprestes** [comment]
Do you mind to translate to English?
Because it looks like request to support http/2 at Macaron and I'm
interested in on it.
Thanks!

Em 14 de jul de 2017 9:52 AM, "myml" <notifications@github.com> escreveu:

**Comment by myml** [comment]
@jeffprestes  ok,please forgive my bad English

**Comment by jeffprestes** [comment]
Hi Myml,

No worries. You don't need to apologise. Actually, what I'd like to know if
with this code sent by you we were able to add HTTP/2 support to a Macaron
App. This would be very interesting to the platform and I'd love to help
you.

Thanks in advance.

Em 15 de jul de 2017 2:25 AM, "myml" <notifications@github.com> escreveu:

@jeffprestes <https://github.com/jeffprestes> ok,please forgive my bad
English

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/go-macaron/macaron/issues/136#issuecomment-315511113>,
or mute the thread

**Comment by myml** [comment]
@jeffprestes  I will try it

**Comment by myml** [comment]
I succeeded!
Reference [response_writer.go#L88](https://github.com/go-macaron/macaron/blob/master/response_writer.go#L88)
add code 
```
func (rw *responseWriter) Push() (http.Pusher, error) {
	pusher, ok := rw.ResponseWriter.(http.Pusher)
	if !ok {
		return nil, fmt.Errorf("the ResponseWriter doesn't support the Pusher interface")
	}
	return pusher
}
```
and   add  method `Push() (http.Pusher, error)` to [`ResponseWriter interface` ](https://github.com/go-macaron/macaron/blob/master/response_writer.go#L27)
This is ok!

example
```
m.Get("/", func(ctx *macaron.Context) {
	pusher, err := ctx.Resp.Push()
	if err != nil {
		log.Panic(err)
	}
	pusher.Push("/test", nil)
})
m.Get("/test", func(ctx *macaron.Context) {
	log.Println("succeed")
})
```
output `succeed`

But i have no experience for pull requests

**Comment by jeffprestes** [comment]
Hey Myml,

Congratulations! Your code looks great. I'm gonna try it later. But I am
just wondering if we should create a mechanism to scan the HTML or Jade/pug
template file when ctx.HTML is called and automatically send the case,
jpeg, PNG and js file detected. What do you think about this idea?
About the PR I don't know either but let's figure out together :)

Em 16 de jul de 2017 2:45 AM, "myml" <notifications@github.com> escreveu:

I succeeded!
Reference response_writer.go#L88
<https://github.com/go-macaron/macaron/blob/master/response_writer.go#L88>
add code

func (rw *responseWriter) Push() (http.Pusher, error) {
	pusher, ok := rw.ResponseWriter.(http.Pusher)
	if !ok {
		return nil, fmt.Errorf("the ResponseWriter doesn't support the
Pusher interface")
	}
	return pusher
}

and add method Push() (http.Pusher, error) to ResponseWriter interface
<https://github.com/go-macaron/macaron/blob/master/response_writer.go#L27>
This is ok!

example

m.Get("/", func(ctx *macaron.Context) {
	pusher, err := ctx.Resp.Push()
	if err != nil {
		log.Panic(err)
	}
	pusher.Push("/test", nil)
})
m.Get("/test", func(ctx *macaron.Context) {
	log.Println("succeed")
})

output succeed

But i have no experience for pull requests

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/go-macaron/macaron/issues/136#issuecomment-315587462>,
or mute the thread

**Comment by myml** [comment]
@jeffprestes  good idea,But [http2 push and browser cache](https://github.com/h2o/h2o/issues/355) is the need to pay attention

**Comment by Unknwon** [comment]
Hi.. I believe `http.Pusher` only exists since Go 1.8, needs a little special care on file structure, but I'll do it. Thank you both!

**Comment by jeffprestes** [comment]
@Unknwon thanks for your attention.
I am implementing and testing @myml suggestion and it works well. I think it's a good starting point for the change into the file structure.
Again, thanks and count on us for any tests or questions.

**Comment by jeffprestes** [comment]
Hey @unknwon we are now at go 1.14 is there a way to accept this PR? 
Because I had to implement this into go-macaron in my vendor folder version and I am facing issues to migrate my application to use go mod (and I believe other devs too)

**Comment by unknwon** [comment]
Yeah, which PR are you referring?

**Comment by unknwon** [comment]
Close as implemented.
